model_type: "deepar"
registered_model_name: "rainfall_deepar"
hidden_size: 128
num_layers: 2
epochs: 50
patience: 10
batch_size: 256
lr: 1e-4
probabilistic: true
model_path: "models/rainfall_deepar.pth"
