model_type: "tcn"
registered_model_name: "rainfall_tcn"
num_channels: [32, 32, 32]
kernel_size: 2
epochs: 50
patience: 10
batch_size: 256
lr: 1e-4
probabilistic: false
model_path: "models/rainfall_tcn.pth"
