hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    optuna_config:
      direction: minimize
      n_trials: 20
      n_jobs: 1
      sampler:
        _target_: optuna.samplers.TPESampler
        seed: 42

    params:
      model_cfg.hidden_size: choice(64, 128, 256)
      model_cfg.num_layers: choice(1, 2, 3)
      model_cfg.lr: loguniform(1e-5, 1e-3)
      model_cfg.batch_size: choice(128, 256, 512)
